extends: ["spectral:oas", "spectral:asyncapi", "spectral:arazzo"]

rules:
  paths-kebab-case:
    description: "Paths should be kebab-case"
    message: " {{property}} should be kebab-case"
    severity: "warn"
    given: "$.paths[*]~"
    then:
      function: "pattern"
      functionOptions: 
        match: "^[a-z0-9]+(-[a-z0-9]+)*$"