// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  portfolioSidebar: [
    // "intro",
    {
      type: "doc",
      label: "Introduction to my Portfolio",
      id: "intro", // 👈 this doc opens when category itself is clicked
    },
    {
      type: "category",
      items: [
         {
          type: 'doc',
          label: 'Introduction to Product',
          id: 'documentation-tooling/intro',
        },
        {
          type: 'doc',
          label: 'Getting Started',
          id:'documentation-tooling/getting-started'
        },
        {
          type: 'category',
          label: 'User Guides',
          items: [
            'documentation-tooling/user-guide/tutorials',
            'documentation-tooling/user-guide/required-properties',
            'documentation-tooling/user-guide/optional-properties',
          ],
        },
      ],
      label: "Documentation Tooling & Static Site Generators",
    },
  ],
};

export default sidebars;
